name: CD

on:
  workflow_run:
    workflows: ["CI"]  # Name of our CI workflow
    types:
      - completed # Only run if the CI pipeline has completed

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  # # Print the commit message of the last commit
  # deploy:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event.workflow_run.conclusion == 'success' }}
  #   steps:
  #     - name: Print SHA and commit message
  #       run: |
  #         echo "SHA: ${{ github.event.workflow_run.head_commit.id }}"
  #         echo "Message: ${{ github.event.workflow_run.head_commit.message }}"

  # Docker image build and push to Dockerhub
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
              ${{ vars.DOCKERHUB_USERNAME }}/calculator:${{ github.sha }},
              ${{ vars.DOCKERHUB_USERNAME }}/calculator:latest
