name: CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write
  actions: read


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest



# jobs:
#   build_image:
#     runs-on: ubuntu-latest

#     steps:
#       # Checkout code
#       - name: Checkout code
#         uses: actions/checkout@v3
      
#       # Python installation
#       - name: Python ${{ matrix.python-version }} installation
#         uses: actions/setup-python@v5
#         with:
#           python-version: ${{ matrix.python-version }}

#       # Install dependencies
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install flake8 pytest


#   push_image:
#     runs-on: ubuntu-latest

#     steps:
#       # Checkout code
#       - name: Checkout code
#         uses: actions/checkout@v3
      
#       # Python installation
#       - name: Python ${{ matrix.python-version }} installation
#         uses: actions/setup-python@v5
#         with:
#           python-version: ${{ matrix.python-version }}

#       # Install dependencies
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install flake8 pytest